uber/tchannel-python

- .travis.yaml
> add travis.yaml

- docs/api.rst
- docs/conf.py
- requirements-docs.txt
> fix sphinx docs

- CHANGES.rst
- GUIDE.rst
- docs/api.rst
- docs/guide.rst
- docs/index.rst
> include the guide in sphinx docs

- .travis.yml
- CHANGES.rst
- tchannel/sync/client.py
- tchannel/sync/thrift.py
- tchannel/thrift/client.py
- tchannel/thrift/util.py
- tests/sync/test_thrift.py
- tests/thrift/test_util.py
- tox.ini
> Fix PyPy support.

- GUIDE.rst
- README.rst
- docs/index.rst
The TOC is currently split in two.
@abhinav
> minor doc tweaks

- CHANGES.rst
- tchannel/tornado/hyperbahn.py
fix the misuse of periodiccallback and fix time.time() error.
@blampe @abhinav @breerly
> Advertise bug

- README.rst
Also fix mobile scaling issues
> Add pypi package badge

- docs/conf.py
- docs/index.rst
> More doc fixes

- CHANGES.rst
- docs/api.rst
- requirements-test.txt
@breerly @abhinav @junchaowu 
API docs are really bad right now :( #30
> re-organize API docs and add sync client

- tchannel/tornado/tchannel.py
> more docs tweaks

- Makefile
- requirements-test.txt
Using Zest's `fullrelease` is enough.
> Remove Makefile release target

- examples/tchannel_server.py
We should add a tox target to run these consistently.
@breerly @abhinav  @Raynos @prashantv
> unbreak x-language target

- .travis.yml
- CHANGES.rst
- setup.py
- tchannel/errors.py
- tchannel/sync/client.py
- tchannel/sync/thrift.py
- tchannel/tornado/tchannel.py
- tests/sync/test_client.py
- tests/tornado/test_tchannel.py
cc @blampe @junchaowu @abhinav
> TChannel.is_listening(), automatic listen on advertise, do not allow listen twice.

- CHANGES.rst
- UPGRADE.rst
- examples/handlers.py
- examples/stream_client.py
- tchannel/tornado/util.py
@junchaowu what is this used for? Refs #33.
> remove print_arg

- CHANGES.rst
- tchannel/thrift/__init__.py
- tchannel/thrift/client.py
- tchannel/tornado/broker.py
- tchannel/tornado/peer.py
- tchannel/tornado/tchannel.py
- tchannel/zipkin/formatters.py
- tchannel/zipkin/tracers.py
- tests/integration/trace/test_zipkin_trace.py
- tests/thrift/test_server.py
- tests/thrift/test_util.py
- tests/tornado/test_dispatch.py
- tests/tornado/test_request.py
add thrift transport header & fix zipkin trace
@breerly @abhinav
> add thrift transport header

- examples/handlers.py
- examples/raw_client.py
- examples/raw_server.py
- examples/stream_client.py
- examples/thrift_examples/client.py
- tests/test_examples.py
Reverts uber/tchannel-python#57
> Revert "Address test_examples flakiness."

- .gitignore
- hooks/pre-commit
- scripts/install-hooks.sh
Run scripts/install-hooks.sh to use.
(We forgot to add the license blurb for some of the new files since we moved to this repo.)
@breerly @junchaowu
> Add pre-commit hook and a script to set it up.

- docs/api.rst
- tchannel/testing/vcr/__init__.py
- tchannel/testing/vcr/cassette.py
- tchannel/testing/vcr/exceptions.py
- tchannel/testing/vcr/patch.py
- tchannel/testing/vcr/record_modes.py
- tchannel/testing/vcr/server.py
- tchannel/testing/vcr/yaml.py
- tests/testing/vcr/test_cassette.py
- tests/testing/vcr/test_server.py
Also add some documentation.
Note: There's an xfail of one of the VCR tests pending a fix to the patching logic.
@breerly @junchaowu @blampe
> Implement record modes for VCR.

- tchannel/event.py
- tchannel/tornado/dispatch.py
- tests/test_event.py
- tests/tornado/test_dispatch.py
refs #72 
@junchaowu @breerly @abhinav
> add an event hook for application errors

- requirements-test.txt
- tests/test_examples.py
> fix flakey example tests

- GUIDE.rst
@junchaowu @breerly @abhinav @aegarbutt
> fix hyperbahn ports

- GUIDE.rst
Tweaks needed after running through the guide together this afternoon.
@junchaowu @abhinav @breerly @rf @jcorbin
> guide tweaks

- GUIDE.rst
- examples/keyvalue/keyvalue/server.py
- separate server run from ioloop start
- add listening print
- use an optional hostlist for advertise
- update tcurl invocation for new v4.10 options (-H and -t file)
r @abhinav @junchaowu
> Improve tcurl doc

- CHANGES.rst
- examples/simple/thrift/client.py
- tchannel/__init__.py
- tchannel/thrift/__init__.py
- tchannel/thrift/module.py
- tests/schemes/test_thrift.py
- tests/thrift/test_module.py
> rename from_thrift_module to thrift_request_builder

- CHANGES.rst
- tchannel/schemes/thrift.py
- tests/schemes/test_thrift.py
> Request in tchannel.thrift should be required

- tchannel/tornado/connection.py
> stream_request doesn't need to be a callback

- tchannel/tornado/tchannel.py
> receive_call isn't a coroutine

- tests/test_examples.py
> stop writing .coverage files inside examples directory

- .gitignore
> let git ignore .idea/ generated from pycharm

- CHANGES.rst
- examples/benchmark/thrift/client.py
- examples/benchmark/thrift/server.py
- examples/simple/json/client.py
- examples/simple/json/server.py
- examples/simple/raw/client.py
- examples/simple/raw/server.py
- examples/simple/thrift/client.py
- examples/simple/thrift/server.py
- tchannel/__init__.py
- tchannel/response.py
- tchannel/retry.py
- tchannel/schemes/__init__.py
- tchannel/schemes/json.py
- tchannel/schemes/raw.py
- tchannel/schemes/thrift.py
- tchannel/serializer/json.py
- tchannel/serializer/raw.py
- tchannel/serializer/thrift.py
- tchannel/tchannel.py
- tchannel/thrift/module.py
- tchannel/transport.py
- tests/schemes/test_json.py
- tests/schemes/test_raw.py
- tests/schemes/test_thrift.py
- tests/serializer/test_serializer_json.py
- tests/serializer/test_serializer_raw.py
- tests/serializer/test_serializer_thrift.py
- tests/test_tchannel.py
- tests/thrift/test_module.py
Setup the pre commit hook. These patch will add license for newly added file.
> add changelog for request handler change

- CHANGES.rst
- setup.cfg
- tchannel/tornado/peer.py
- tests/integration/test_retry.py
- tests/test_tchannel.py
Resolves #115.
@junchaowu @breerly @abhinav
> fix forking issue

- examples/benchmark/thrift/client.py
- examples/benchmark/thrift/server.py
- tests/test_examples.py
> fix benchmark example

- tchannel/tchannel.py
> Clarify timeout is in MS

- CHANGES.rst
- tchannel/tchannel.py
- tests/test_tchannel.py
> add hooks property for the new TChannel

- CHANGES.rst
- examples/simple/json/client.py
- examples/simple/json/server.py
- examples/simple/raw/client.py
- examples/simple/raw/server.py
- examples/simple/thrift/client.py
- examples/simple/thrift/server.py
- tchannel/__init__.py
- tchannel/response.py
- tchannel/retry.py
- tchannel/schemes/__init__.py
- tchannel/schemes/json.py
- tchannel/schemes/raw.py
- tchannel/schemes/thrift.py
- tchannel/tchannel.py
- tchannel/thrift/module.py
- tchannel/thrift/serializer.py
- tchannel/tornado/dispatch.py
- tchannel/transport.py
- tests/schemes/test_json.py
- tests/schemes/test_raw.py
- tests/schemes/test_thrift.py
- tests/test_tchannel.py
- tests/thrift/test_module.py
> backport exception logging from 0.16

- CHANGES.rst
- tchannel/sync/thrift.py
- tchannel/thrift/client.py
- tests/schemes/test_thrift.py
> make client_for compatible with new TChannel

- setup.py
Changing address temporarily until we have a public address for the project.
CC @jwolski
> Update email address

- CHANGES.rst
- tchannel/tchannel.py
> add is_listening to the TChannel

- CHANGES.rst
- tchannel/tornado/peer.py
> Allow 0 retries

- tchannel/tornado/tchannel.py
> update the parameter for advertise, routers=None

- CHANGES.rst
- tchannel/tchannel.py
- tests/test_tchannel.py
> make listen thread safe.

- CHANGES.rst
- tchannel/messages/call_request.py
- tchannel/tornado/message_factory.py
- tests/test_message_factory.py
> fix ttl not set bug

- tchannel/sync/client.py
> update the example of sync client in the comments to use the right timeout unit.

- UPGRADE.rst
- docs/api.rst
- tchannel/context.py
- tox.ini
@junchaowu 
I think docs were broken due to the warning in `UPGRADE.rst`.
> add docs around request context

- CHANGES.rst
- setup.py
- tchannel/request.py
- tchannel/schemes/json.py
- tchannel/schemes/raw.py
- tchannel/schemes/thrift.py
- tchannel/tchannel.py
- tchannel/zipkin/trace.py
- tchannel/zipkin/tracers.py
- tests/integration/json/test_json_server.py
- tests/integration/test_client_server.py
- tests/integration/test_error_handling.py
- tests/integration/trace/test_zipkin_trace.py
- tests/mock_server.py
- tests/testing/vcr/test_server.py
Lets move this fix to a patch release, `0.16.6`, before cutting `0.17.0`.
> Cherry pick zipkin fix

- GUIDE.rst
- UPGRADE.rst
> add a version note about the guide

- CHANGES.rst
- tchannel/testing/vcr/cassette.py
> vcr shouldn't match on hostport

- GUIDE.rst
- UPGRADE.rst
> add a note about no breaking changes between 0.16/0.17

- tchannel/zipkin/annotation.py
- tchannel/zipkin/formatters.py
- tchannel/zipkin/zipkin_trace.py
- tests/integration/trace/test_zipkin_trace.py
@breerly @blampe 
cc @rf @prashantv
> Add binary annotation support for zipkin trace.

- tchannel/zipkin/annotation.py
- tchannel/zipkin/formatters.py
- tchannel/zipkin/zipkin_trace.py
- tests/integration/trace/test_zipkin_trace.py
Reverts uber/tchannel-python#192
> Revert "Add binary annotation support for zipkin trace."

- Makefile
- setup.py
In order to get to 1.0, we need our child dependencies to commit to stable API's - let's start with threadloop which went 1.0 today.
> Use threadloop >=1<2

- CHANGES.rst
- UPGRADE.rst
- tchannel/serializer/json.py
- tests/integration/json/test_json_server.py
- tests/serializer/test_serializer_json.py
- tests/sync/test_client.py
Quick hack, will fix the inheritance tomorrow. Resolves #117.
@breerly @junchaowu
> json headers are map[string]string

- GUIDE.rst
Make tchannel name and tcurl example statements consistent.
> Fix tcurl statements to work with tchannel name

- tchannel/sync/client.py
Fixes #210.
@abhinav @breerly @junchaowu
> document fanout in the sync client

- tchannel/sync/client.py
> fix timeout unit in the docs

- CHANGES.rst
- setup.py
Going to cut a new patch with this.
@breerly @junchaowu @abhinav @jacorreia
> tchannel is compatible with thriftrw 0.4

- tchannel/thrift/rw.py
> thriftrw is not experimental in 0.18

- tchannel/deprecate.py
- tchannel/singleton.py
- tchannel/sync/singleton.py
- tests/sync/test_singleton.py
- tests/test_singleton.py
@breerly I think you need to run `scripts/install_hooks.sh` :)
@abhinav @junchaowu
> add missing headers

- setup.py
> compatibility with thriftrw 0.5

- CHANGES.rst
- tchannel/tornado/peer.py
- tests/tornado/test_hyperbahn.py
- tests/tornado/test_peer.py
> Retry network errors while connecting

- CHANGES.rst
- setup.py
> Support thriftrw 0.5

- CHANGES.rst
> add change log for new release

- CHANGES.rst
- tchannel/tornado/tchannel.py
> ipv4 only to work around address already in use error

- tchannel/tornado/message_factory.py
- tests/test_message_factory.py
> refactor message factory to reduce code duplication

- requirements-test.txt
- setup.py
we already get futures implicitly through threadloop
> remove explicit dep on futures

- Makefile
- setup.cfg
- tests/conftest.py
- tests/integration/thrift/test_thriftrw.py
- tests/integration/thrift/test_tornado_client.py
- tests/testing/vcr/integration/test_sync_client.py
- tests/testing/vcr/integration/test_vcr.py
- tests/util.py
> Prevent all tests from using thrift code generation

- CHANGES.rst
> add a note about removing apache thrift support

- Makefile
- setup.py
> resolve lint issues in setup.py

- CHANGES.rst
- benchmarks/test_peer_selection.py
- hooks/pre-commit
- requirements-test.txt
- tchannel/testing/vcr/patch.py
- tchannel/tornado/connection.py
- tchannel/tornado/peer.py
- tchannel/tornado/tchannel.py
- tests/integration/test_retry.py
- tests/tornado/test_connection.py
- tests/tornado/test_peer.py
> Improve peer selection performance (patch)

- CHANGES.rst
- tchannel/tornado/hyperbahn.py
@lucasmarshall @abhinav @breerly @junchaowu
> reduce advertise errors to warnings

- CHANGES.rst
- tchannel/tornado/connection.py
- tchannel/tornado/hyperbahn.py
@junchaowu @breerly @abhinav @Raynos
> add a timeout to hyperbahn advertisement

- CHANGES.rst
- tchannel/glossary.py
- tchannel/tornado/dispatch.py
- tchannel/tornado/peer.py
- tests/test_tchannel.py
- tests/tornado/test_dispatch.py
Limit the size of arg1 to 16KB that matches protocol.
> Limit the size of arg1 to 16 KB

- CHANGES.rst
- setup.py
- tchannel/thrift/rw.py
> use thriftrw >=1<2

- CHANGES.rst
- UPGRADE.rst
- requirements-test.txt
- setup.py
- tchannel/thrift/rw.py
Other things from #295 have been punted to 0.21.
> Preparing for 0.20 release.

- CHANGES.rst
- tchannel/tornado/connection.py
- tchannel/tornado/peer.py
- tchannel/tornado/request.py
- tests/integration/test_client_server.py
- tests/tornado/test_connection.py
https://github.com/uber/tchannel-python/pull/291
> cherry pick removing assertion patch

- tchannel/tornado/dispatch.py
this is going to fix  https://github.com/uber/tchannel-python/issues/311
> Add more descriptive message to the unexception error message.

- CHANGES.rst
- setup.py
- tchannel/__init__.py
Also, read version number in setup.py from __init__.py.
> Revert bad release

- GUIDE.rst
> Fix typo in guide

- tchannel/tornado/connection.py
- tchannel/tornado/peer.py
- tchannel/tornado/util.py
- tests/tornado/test_connection.py
This will be used for peer selection.
> Add list to track outbound pending req/res

- tchannel/request.py
- tchannel/schemes/json.py
- tchannel/schemes/raw.py
- tchannel/schemes/thrift.py
- tchannel/tchannel.py
- tchannel/transport.py
- tests/test_dispatch.py
See uber/tchannel#1405 for details.
Closes #324.
> Add support for rd transport header.

- CHANGES.rst
- GUIDE.rst
- setup.py
- tchannel/__init__.py
- tchannel/tornado/dispatch.py
- tchannel/tornado/hyperbahn.py
> Merge master into mash release branch

- tchannel/zipkin/tracers.py
- tests/integration/trace/test_zipkin_trace.py
> disable retry on tchannel zipkin submit

- CHANGES.rst
- tchannel/zipkin/trace.py
- tchannel/zipkin/zipkin_trace.py
- tests/integration/trace/test_zipkin_trace.py
> Add sampling logic into the zipkin trace

- CHANGES.rst
- tchannel/serializer/json.py
- tests/schemes/test_json.py
- tests/serializer/test_serializer_json.py
Pending confirmation that it was wrong
> Fix JSON argscheme header encoding

- tchannel/zipkin/formatters.py
- tchannel/zipkin/tcollector.thrift
- tchannel/zipkin/tracers.py
- tests/integration/trace/test_zipkin_trace.py
Based on Yuri's request adding the spanHost field.
@abhinav @blampe @breerly 
cc @prashantv  @Raynos
> Add spanHost field into tcollector submit

- CHANGES.rst
- tchannel/tchannel.py
- tchannel/zipkin/trace.py
- tests/integration/trace/test_zipkin_trace.py
this patch fixes #346
@breerly @blampe @abhinav
> FIX the infinite trace submit problem

- setup.py
> add classifiers

- CHANGES.rst
- tchannel/sync/client.py
- tchannel/sync/thrift.py
- tests/conftest.py
- tests/schemes/test_thrift.py
- tests/sync/test_client.py
- tests/tornado/test_peer.py
> don't start the threadloop until we have work to do

- tchannel/peer_heap.py
- tchannel/tornado/peer.py
> Update choose method to use smallest util function

- tchannel/request.py
- tchannel/response.py
- tchannel/tchannel.py
- tchannel/tornado/dispatch.py
- tchannel/transport.py
> Add to/from_dict for req/res TransportHeaders

- .gitignore
> Add .cache into gitignore

- CHANGES.rst
- setup.py
> Tornado 4.3 is required.

- .travis.yml
- Makefile
- benchmarks/test_roundtrip.py
- tox.ini
I want something that gives us some measurable data on performance. I'm going to be killing some coroutines and I want to be able to confirm that it's helping.
@abhinav @breerly
> Add a roundtrip benchmark

- CHANGES.rst
- tchannel/tornado/connection.py
> Fix an unhelpful error message

- CHANGES.rst
- tchannel/tornado/connection.py
> Reduce read errors to info

- CHANGES.rst
- tchannel/tchannel.py
- tests/test_tchannel.py
> Make TChannel.advertise() idempotent and thread safe.

- tchannel/tornado/connection.py
- tests/tornado/test_connection.py
If the IOStream has already been closed by the time read_message is called, it
will fail with a synchronous StreamClosedError which read_message needs to
catch.
CC @blampe @breerly @junchaowu
> connection: read_message should propagate StreamClosedError

- CHANGES.rst
- tchannel/tornado/connection.py
This is causing way too much confusion.
@abhinav
> reduce unconsumed messages to info

- CHANGES.rst
- tchannel/tornado/connection.py
Should resolve #369.
@abhinav @junchaowu
> catch StreamClosedError on handshake

- CHANGES.rst
- tchannel/zipkin/zipkin_trace.py
Resolves #364.
@abhinav @junchaowu
> reduce default sample rate

- tchannel/tornado/dispatch.py
This fixes yet another "Future exception was never retrieved" issue.
> Log all response write errors except StreamClosedErorrs

- tchannel/schemes/json.py
- tchannel/schemes/raw.py
- tchannel/schemes/thrift.py
> improve retry_limit docs

- tchannel/tornado/peer.py
`raise error` eliminates the stack trace from the original failure.
This is being merged into the queue-terminate branch rather than master.
> Calls should reraise with the origianl traceback when retries run out

- CHANGES.rst
- tchannel/tornado/hyperbahn.py
> Reduce advertise interval frequency to once every 3 minutes

- CHANGES.rst
- benchmarks/test_concurrent_requests.py
- benchmarks/test_peer_selection.py
- tchannel/container/heap.py
- tchannel/peer_heap.py
- tchannel/peer_strategy.py
- tchannel/tornado/connection.py
- tchannel/tornado/dispatch.py
- tchannel/tornado/peer.py
- tchannel/tornado/tchannel.py
- tests/conftest.py
- tests/container/test_heap.py
- tests/test_event.py
- tests/test_peer_heap.py
- tests/test_peer_strategy.py
- tests/tornado/test_connection.py
- tests/tornado/test_peer.py
We want to release these changes without most of the breaking changes in the `mash` release branch. @junchaowu, can you take a close look at this since you're the primary author of this change? Especially, make sure I didn't miss anything in the cherry-pick.
CC @blampe @breerly
> Cherry pick heap-based peer selection into master

- tests/thrift/test_multiple_services.py
@blampe @breerly @junchaowu 
CC @prashantv @kriskowal
> Test: Verify Thrift service name used for inherited methods

- CHANGES.rst
- tchannel/testing/vcr/patch.py
> Add a timeout to the VCR proxy call

- CHANGES.rst
- tchannel/tornado/dispatch.py
- tchannel/tornado/response.py
- tchannel/tornado/stream.py
- tests/schemes/test_thrift.py
> make UnexpectedError a little more debuggable

- CHANGES.rst
- tchannel/tornado/message_factory.py
> Remove a warning for unconsumed errors

- .travis.yml
- CHANGES.rst
- tchannel/tchannel.py
- tchannel/tornado/tchannel.py
- tests/test_tchannel.py
@blampe @kriskowal @junchaowu @abhinav
> Allow SO_REUSEPORT

- CHANGES.rst
- setup.py
- tchannel/tornado/tchannel.py
> constraint to tornado 4.3

- CHANGELOG.rst
- tchannel/testing/vcr/cassette.py
- tests/testing/vcr/test_cassette.py
See https://github.com/uber/tchannel-python/issues/419
> Add cache for cassette yaml files

- tchannel/tracing.py
This is a backport of #436 to the 0.27 release.
CC @yurishkuro
> Ignore Tracing field with empty/zero TraceID (#436)

- CHANGELOG.rst
- tchannel/tchannel.py
> Turn tracing on by default, but with Noop tracer

- CHANGELOG.rst
- tchannel/schemes/json.py
- tchannel/schemes/raw.py
- tchannel/schemes/thrift.py
- tchannel/tchannel.py
- tests/test_tchannel.py
> Add caller_name argument to TChannel.call and friends

- CHANGELOG.rst
- tchannel/tchannel.py
- tchannel/tornado/hyperbahn.py
- tchannel/tornado/tchannel.py
> Add jitter argument to hyperbahn advertise()

- CHANGELOG.rst
- tchannel/tchannel.py
- tests/test_tchannel.py
Resolves #452
@blampe @breerly @prashantv @willhug
> Disallow empty service names

- CHANGELOG.rst
- tchannel/tornado/connection.py
- tests/tornado/test_connection.py
Resolves #450
@prashantv @breerly @blampe
> Outgoing handshakes: Time out after 5 seconds

- tchannel/tornado/connection.py
> loop: first _step should set loop running right away

- requirements.txt
- setup.py
- tchannel/schemes/json.py
- tchannel/schemes/thrift.py
- tchannel/tracing.py
Depends on merging [this one](https://github.com/uber-common/opentracing-python-instrumentation/pull/31)
Looking for comments on approach
> Added Client Interceptors to tracing implementation

- .travis.yml
- CHANGELOG.rst
- requirements-test.txt
- tchannel/testing/vcr/config.py
- tchannel/tornado/connection.py
- tests/testing/vcr/integration/test_vcr.py
- tests/tornado/test_connection.py
- tox.ini
Explicitly support py36 and py37
> Updating to py37 compatibility
